### ISSUE TITLE
Returns undefined in ie9.

### ISSUE THREAD

**Issue by mime55** [hayageek/jQuery-URL-shortener#1]
Hi,

I do not have much experience with jQuery, so maybe this is a well known bug with ie9. Anyway - the html is not passed to the container when clicking the button.

Edit: I checked the variable with the short URL, and it is returning "undefined".

It would be nice if you could provide a workaround within the plugin.
Thanks for your work!

regards

**Comment by hayageek** [comment]
I have fixed the issue. Because of cross domain , IE 9 not sending request.  I have changed the API calls also. check the documentation.

Working:
http://hayageek.com/examples/jquery/url-shortener/example.php

**Comment by mime55** [comment]
Thanks, working great!
